### ISSUE TITLE
[Linux Server] Audio cuts out at random

### ISSUE THREAD

**Issue by ChrisChrome** [Jesus-QC/AudioPlayer#19]
At random, and only with certain audio files, it will just cut out and play static. I've looked into the encoding of the files that work and don't and can't seem to find anything special between them.
Both myself (Chris Chrome#9158) and another server owner I'm in contact with (Oxygen//BreathableAtmosphere#2700)

We both run our servers under Pterodactyl/Wings, I have no Idea if that could be responsible for it.
If it's some simple misconfiguration issue, sorry for the trouble

**Comment by Jesus-QC** [comment]
Should be fixed, if not please reopen the issue
