### ISSUE TITLE
Bullet Holes not appearing

### ISSUE THREAD

**Issue by DinoNuggets2** [Jesus-QC/AudioPlayer#21]
So my server has had a problem for a while where bullet holes don't appear. I went through my entire plugin list, disabled each one and enabled them all one by one, and found that Audio Player interferes with bullet holes appearing..? If needed I can add LA logs if necessary

This issue happens with Plugin version 2.0.0.

**Comment by Jesus-QC** [comment]
Oh, it makes a lot of sense, sorry for that, this plugin wont have new releases until 12.0, I recomend you using the older version.
