### ISSUE TITLE
Spawn audios don't end

### ISSUE THREAD

**Issue by DinoNuggets2** [Jesus-QC/AudioPlayer#5]
After a spawn wave audio ends, the Dedicated Server still plays a static sound through the global chat.

Also since I am making this I have a suggestion:
Possibly add a way to disable the Dedicated Server name appearing when it plays an audio. I don't know if this is possible though because base-game always shows the person's nametag while using a global chat.

**Comment by Jesus-QC** [comment]
> After a spawn wave audio ends, the Dedicated Server still plays a static sound through the global chat.
> 
> Also since I am making this I have a suggestion: Possibly add a way to disable the Dedicated Server name appearing when it plays an audio. I don't know if this is possible though because base-game always shows the person's nametag while using a global chat.

Not possible, and fixed

**Comment by Jesus-QC** [comment]
Check latest release
