### ISSUE TITLE
Audios doesnt finish

### ISSUE THREAD

**Issue by CosmosZvezdo4kin** [Jesus-QC/AudioPlayer#6]
There is no point in using the loop command now, because the IEnumerator "PlayFromFile" argument loop will always have the value false. In fact, the LoopMusic field is not even used as intended.

**Comment by Jesus-QC** [comment]
> There is no point in using the loop command now, because the IEnumerator "PlayFromFile" argument loop will always have the value false. In fact, the LoopMusic field is not even used as intended.

What? It does work

**Comment by Jesus-QC** [comment]
Also, it wont always be false

**Comment by Jesus-QC** [comment]
https://github.com/Jesus-QC/AudioPlayer/blob/62607574663408a2a89d79b39bfd9b33679b0c9b/AudioPlayer/Core/Components/CustomMpegMicrophone.cs#L94

**Comment by Jesus-QC** [comment]
It is used there

**Comment by Jesus-QC** [comment]
The issue is that some audios length is calculated wrongly, therefore they dont finish.

**Comment by Jesus-QC** [comment]
And it is already being worked

**Comment by Jesus-QC** [comment]
Please dm me the audio so I can fix it soon

**Comment by Jesus-QC** [comment]
Couldnt replicate
