### ISSUE TITLE
(Windows) Music does not play.

### ISSUE THREAD

**Issue by WoofWolfGG** [Jesus-QC/AudioPlayer#7]
When I enter a command that starts playing the audio, the plugin responds with the message "Playing...". But nothing happens. debug-log attached
![image](https://user-images.githubusercontent.com/77447803/172044882-9318b1d3-6163-496b-8afb-3734afe2173f.png)

**Comment by Jesus-QC** [comment]
> When I enter a command that starts playing the audio, the plugin responds with the message "Playing...". But nothing happens. debug-log attached ![image](https://user-images.githubusercontent.com/77447803/172044882-9318b1d3-6163-496b-8afb-3734afe2173f.png)

Send here the mp3 file

**Comment by WoofWolfGG** [comment]
![image](https://user-images.githubusercontent.com/77447803/172048090-837d99c5-01ff-4b14-995b-6bdc58d18c70.png)

Attached to GDrive
https://drive.google.com/file/d/1uDEjOTS6YBIpe5CK362GHnAWgQFPMo6Q/view?usp=sharing

**Comment by Jesus-QC** [comment]
Are you using windows?

**Comment by Jesus-QC** [comment]
Because with linux I cant replicate it.

**Comment by WoofWolfGG** [comment]
> Are you using windows?

Yes, windows

**Comment by Jesus-QC** [comment]
Investigating the issue

**Comment by Jesus-QC** [comment]
Should be fixed with the last release
